# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 5
VAGRANT_VM_PROVIDER = "virtualbox"
ANSIBLE_RAW_SSH_ARGS = []

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |config|
    config.memory = 2048
    config.cpus = 2
  end

  config.vm.define "jbs" do |jbs|
    jbs.vm.host_name = 'jbs'
    jbs.vm.network "private_network", ip: "192.168.111.111"
    jbs.vm.provision "ansible" do |ansible|
      ansible.playbook = "host.yml"
      ansible.inventory_path = "inventory/vagrant"
      ansible.limit = 'all'
    end
  end

  (1..N-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS << "-o IdentityFile=.vagrant/machines/machine#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..N).each do |machine_id|
    config.vm.define "tca#{machine_id}" do |machine|
      machine.vm.hostname = "tca#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.111.10#{machine_id}"

      machine.vm.provision :ansible do |ansible|
        ansible.limit = "all"
        ansible.playbook = "tc-agent.yml"
        ansible.inventory_path = "inventory/vagrant"
        ansible.verbose = "-v"
        ansible.raw_ssh_args = ANSIBLE_RAW_SSH_ARGS
      end
    end
  end
end
