Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |config|
    config.memory = 4096
    config.cpus = 2
  end

  config.vm.define "jbs" do |jbs|
    jbs.vm.host_name = 'jbs'
    jbs.vm.network "private_network", ip: "192.168.111.111"
    jbs.vm.provision "ansible" do |ansible|
      ansible.playbook = "host.yml"
      ansible.inventory_path = "inventory/vagrant"
      ansible.limit = 'all'
    end
  end

  config.vm.define "tca01" do |tca01|
    tca01.vm.host_name = 'tca01'
    tca01.vm.network "private_network", ip: "192.168.111.122"
    tca01.vm.provision "ansible" do |ansible|
      ansible.playbook = "tc-agent.yml"
      ansible.inventory_path = "inventory/vagrant"
      ansible.limit = 'all'
    end
  end

  config.vm.define "tca02" do |tca02|
    tca02.vm.host_name = 'tca02'
    tca02.vm.network "private_network", ip: "192.168.111.133"
    tca02.vm.provision "ansible" do |ansible|
      ansible.playbook = "tc-agent.yml"
      ansible.inventory_path = "inventory/vagrant"
      ansible.limit = 'all'
    end
  end


end
